### PR TITLE
feat(resource): add os details in machine env

### PR DESCRIPTION
**Pull request by zxq-bit**
**What this PR does / why we need it**:

- update machine env os info about

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
update machine env os info about
```

### CODE REVIEW

**Comment by zxq-bit** [comment]
@liubog2008 PTAL

**Comment by liubog2008** [comment]
@kdada

**Pull request merged**
